theme = "m"
baseURL = "https://danielcallejo.dev/"
languageCode = 'en-us'
title = 'x0l4dn4'

[params]
author = "Daniel Callejo"
description = 'Personal blog to upload all my notes and stuff'
avatar='icon/owl.png'
favicon='icon/hood.ico'

[params.style]
darkestColor = "#020408"
darkColor   = "#04070d"
lightColor  = "#0a0f18"
lightestColor = "#0f1a25"
primaryColor  = "#00f7ff"


[[params.social]]
icon = "brand-github"
name = "GitHub"
url = "https://github.com/x0l4dn4"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[caches]
  [caches.assets]
    maxAge = -1

  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1

